### ISSUE TITLE
Create maintenance branch on x.y.0 releases if it doesn't exist

### ISSUE THREAD

**Issue by alcaeus** [doctrine/automatic-releases#10]
Closing a milestone for any x.y.0 release (including pre-releases like `1.2.0-Beta1`) should create a new branch for this release (e.g. 1.2.x) if it doesn't exist. The release is then tagged from this support branch, with `master` being freed up for being a new minor/major version.

**Comment by sstok** [comment]
FYI. https://github.com/rollerworks/version

**Comment by alcaeus** [comment]
Fixed in #23.
