### ISSUE TITLE
Support pre-releases

### ISSUE THREAD

**Issue by alcaeus** [doctrine/automatic-releases#25]
The tool currently doesn't support alpha, beta or RC releases. Versioning should detect pre-release versions and:
* create the appropriate release branch if necessary
* roll the release as usual, except that the GitHub release should be marked as pre-release
* trigger merge-up as usual

The tool should also check if the release is possible. This expands on the checks already present for regular releases. To check this, the following is valid:
* alpha < beta < RC
* the pre-release number may only reset when switching to a higher stability
* pre-releases for patch versions are:
** forbidden if a newer patch release in any stability in the same minor version exists (e.g. releasing 1.0.0-beta1 when 1.0.1 has been tagged)
** allowed if a newer minor version exists (e.g. releasing 1.0.1-beta1 when 1.1.0 has been tagged)
* pre-releases for minor versions (i.e. 1.1.0) areL
** forbidden if a newer minor release of the same major version has been tagged, regardless of its stability (e.g. releasing 1.1.0-beta1 when 1.2.0 has been tagged)
** allowed if a newer major version exists (e.g. releasing 1.1.0-beta1 when 2.0.0 has been tagged)
* pre-releases for major versions (i.e 2.0.0) are forbidden if a newer major release has been tagged, regardless of its stability (e.g. releasing 2.0.0-beta1 when 3.0.0 has been tagged)

**Comment by Ocramius** [comment]
Probably need to plug in a SemVer comparison library when implementing this

**Comment by Ocramius** [comment]
Moved to https://github.com/laminas/automatic-releases/issues/25
