### ISSUE TITLE
Make sure that all the changes since the last release are associated to the milestone

### ISSUE THREAD

**Issue by morozov** [doctrine/automatic-releases#37]
Right now, for a given pull request, the target branch and the associated milestone are totally independent. It allows for a situation when some changes are released as part of the changes in the branch being tagged but are not listed in the release note. It happens every once in a while.

High-level, the logic is the following:

1. Take all merge commits since the last release.
2. Associate them with pull requests on GitHub and the corresponding issues (via the Fixes and Closes references).
3. If there's a discrepancy, report a problem and halt.
4. Additionally, if some changes need to be excluded from the notes explicitly, there may be a label for that.

**Comment by morozov** [comment]
For the reference: https://github.com/doctrine/dbal/pull/3790#issuecomment-573542117 (happened in a manually managed release).

**Comment by Ocramius** [comment]
Moved to https://github.com/laminas/automatic-releases/issues/27
