### ISSUE TITLE
Allow to use a pre-created GitHub release

### ISSUE THREAD

**Issue by morozov** [doctrine/automatic-releases#38]
The autogenerated release notes may not always be descriptive and user-friendly enough. Especially for minor and major releases. As a package maintainer, I want to be able to fine-tune the text that is generated by the bot before it becomes the content of the git tag and is published on GitHub.

There are two approaches that come to mind:

1. Instead of creating a GitHub release unconditionally, the bot looks up a release draft based on the tag and uses it if it exists.
2. The release is done in stages: 1) The release notes are drafted; 2) The notes are edited and approved; 3) The process continues.

**Comment by Ocramius** [comment]
Seems unnecessary: current release is generated taking milestone description and issues/PRs, and the release can be edited later anyway.
