### ISSUE TITLE
Allow skipping branches when merging up

### ISSUE THREAD

**Issue by alcaeus** [doctrine/automatic-releases#64]
For MongoDB ODM, we continue to support 1.4.x as the last minor release for 1.x. At the same time, we're now going to release 2.1.0, which makes 2.0.x unsupported. Merges after a release should ignore 2.0.x and go straight to 2.1.x. This likely requires us to be able to configure supported branches (or read that information from `.doctrine-project.json`).

**Comment by Ocramius** [comment]
Branch `2.0.x` should likely be deleted, then PRs from `1.4.x` will be merged-up to `2.1.x`.

I haven't tested this carefully, but logic in https://github.com/laminas/automatic-releases/blob/86016a55ee2cfcb6c13d66b47f65f483a3879a11/src/Application/Command/CreateMergeUpPullRequest.php#L74 should already do this.

**Comment by Ocramius** [comment]
Logic for this is a bit messy, but tested: https://github.com/laminas/automatic-releases/blob/86016a55ee2cfcb6c13d66b47f65f483a3879a11/src/Git/Value/MergeTargetCandidateBranches.php#L63-L86
