### ISSUE TITLE
Allow triggering a merge-up without tagging a release

### ISSUE THREAD

**Issue by alcaeus** [doctrine/automatic-releases#7]
Use-case: we currently have three active branches in MongoDB ODM:
* 1.2.x: support branch for the current stable release,
* 1.3.x: development branch for the upcoming 1.x version,
* master: development branch for the upcoming 2.x version.

When tagging a 1.2 release, the merge to 1.3.x is done automatically, but we'd like to follow this up with a merge up to master without tagging a release for 1.3 (since it is not ready to be released yet).

I'm not sure what a good trigger would be, but the following options come to mind (just a collection of ideas, I haven't given this a lot of thought):
* Adding a label to the merge-up pull request that triggers a merge-up to the next branch
* Creating an issue and mentioning the bot username to tell it to merge-up from branch `a` to the next branch

**Comment by Ocramius** [comment]
This can most likely be done: what's missing is to decide what the trigger would be.

Note also that the tool will be a deployed web-app (currently at https://automatic-releases.herokuapp.com/ ), so having an authenticated endpoint is also sufficient.

**Comment by Ocramius** [comment]
Another thing we can do is having two separate hooks that independently do releases and merge up. If you enable both, you get both behaviors.

**Comment by alcaeus** [comment]
In that case, what's the situation where you'd want to trigger a merge-up? Merging a pull request to a branch? That could get quite tiring if merging multiple pull requests in one go.

**Comment by Ocramius** [comment]
This is implemented in https://github.com/laminas/automatic-releases/pull/1

In practice, you can skip the release command when configuring the github action.
